# Baking {#baking}

## Macaron "Endless Vanilla"

For biscuits:

* 150 g almond flour, sifted twice
* 150 g powdered sugar
* 55 g egg whites, aged (from about 1.5 eggs)
* 1 1/2 vanilla pod
* 150 g icing sugar
* 37 g mineral water (without gases)
* 55 g egg whites, aged

For vanilla ganache:

* 200 g heavy cream
* 1 vanilla pod from Mexico
* 1 vanilla pod from Madagascar
* 1 vanilla pod from Tahiti
* 220 grams of white chocolate (Valrhona preferred, but not critical)

Eggs:
You have noticed that I have the term "aged" proteins. This means that the day before you cook macarons, the egg whites need to be removed from the refrigerator, covered with cling film and allowed to stand at room temperature all this time. Such egg whites will become more liquid, they seem to decompose (the structure of the protein is destroyed). As a result, they become more voluminous when whipped.

Ganache:
Cut the vanilla pods in half. Use a knife to remove all the seeds. Add them along with the pods to a saucepan and pour the cream.
Bring to a boil over medium heat. Remove from heat, cover and let sit for 30 minutes.
Break the chocolate into pieces and melt in a water bath.
Heat the cream again. Remove the vanilla pods from the saucepan and gradually pour the vanilla cream into the chocolate in a thin stream, stirring constantly with a whisk so that there are no lumps.
Cover with cling film and refrigerate overnight.

Macarons:
Line a baking sheet with parchment paper. Prepare a cooking syringe or a piping bag with a straight round nozzle.

Macarons are made with a diameter of 3-4 cm. To begin with, while your hand is not trained, you can draw stencils for yourself on parchment paper, on the back side. In France, for example, you can buy baking paper with a stencil already marked or a silicone mat.

Sift almond flour. If large pieces of nuts remain in the sieve, grind them over again or leave them on a biscuit, cake, pie.
Sift almond flour and powdered sugar several times into a bowl.

Remove the seeds from the vanilla pods and add to the almond mixture. Do not stir. Add the first batch of egg whites (55 g) - do not stir.

In a small saucepan, combine water and second powdered sugar and bring to a boil until it reaches 118'C.
Whisk the second 55 g of egg whites until firm.

Gradually pour in the hot syrup in a thin stream. Continue whisking until the mixture is cool and shiny, thick and smooth.

When you lift the whisk, a mass should remain on its tip and not fall. A "nose" of proteins in a bowl, do not stand straight, but "fall". That said, if you turn your bowl of whites upside down, nothing should fall or leak.

Add the resulting Italian meringue (egg whites with hot syrup) to the first mixture.
Stir gently with a spatula while rotating the bowl counterclockwise with the other hand.

The mass should turn out to be homogeneous, soft, pliable. If you raise the spatula, then the drops of dough that will fall down should slowly spread, and not keep their shape. Do not be afraid to interfere - if the dough is poorly mixed, the pasta you have planted will have "tails" on the surface. Otherwise, they will slowly spread and take an even shape.

Place the dough in a syringe or bag and place in even circles on the lined paper.

And leave them to stand at room temperature for 1 hour. This is a very important stage of cooking - a light film forms on the surface of the meringue, due to which they do not crack during baking and a beautiful "skirt" is formed at the bottom.
Heat the oven to 175C.
Bake the cookies for 12-15 minutes. During cooking, 2 times (at the 8th and 10th minutes) very quickly open and close the oven, being careful not to knock.

Take out the finished cookies, grab the edges of the paper and transfer it along with the macarons onto a flat surface. Let cool completely.

A properly baked cookie will easily come off the paper surface.
When the cookies have cooled, fill a syringe or bag with ganache and place a small amount on one half, then close the other.

Refrigerate for 24 hours. Only cooked macaroons are never eaten - the halves will be tough and the whole cream will spread. They need to be given time to "come up", to brew, and then they will get exactly what they are so fond of: crisp crust, tender center and melting filling.

## Upside down cake with nuts and bananas

* 130g butter
* 120g sugar
* 120g flour
* 50g ground roasted nuts
* 3 eggs
* 0.5 tsp baking powder

* 2 bananas
* 50g dark muscovado sugar
* 20g butter

cake pan 10x20cm
oven 170C

First, brush the sides of the mold with softened butter and sprinkle with flour. Combine dark sugar and 20g butter and place on the bottom of the mold.
Prepare the dough. All foods should be at room temperature. Beat butter with sugar.
Add two eggs, one at a time, whisking each time until smooth at maximum mixer speed.
Add the nuts, add the remaining egg and beat the mixture again with a mixer.
Add flour and baking powder, stir on low speed until smooth.
Cut each banana into three pieces lengthwise. Place the cooked bananas in a mold on top of the sugar mixture.
Place the dough on top and tap well with the mold on the table.
Bake at 170C for 50 minutes.
Remove and cut the top off by sliding the knife along the edge of the pan and flip the hot cupcake onto a plate.

## Spicy donuts/muffins from the oven with apples

* Flour - 140 g
* Cinnamon - 1 tsp
* Ginger - 1 tsp
* Baking powder - 1 tsp.
* Sugar - 140 g
* Condensed milk - 100 g
* Egg - 1 piece
* Butter - 25 g
* Apple

In a cup, combine flour (140 g), cinnamon and dried ginger (1 tsp each, I would not add fresh ginger), baking powder (also 1 tsp). And sugar (140 g). Stir the whole mass very well and carefully, because we need the baking powder, and the spices, to be distributed very evenly in the future dough. Of course, you can refuse cinnamon and ginger, or replace / supplement them with other spices - all at your discretion. Further condensed milk (100 g, you can replace with fat sour cream).

Melted butter (25 g). One egg. And at the very end, grate the apple (110-120 g). Traditionally, I take Granny Smith, because he can be found anywhere in Russia. Here you can play with filling. Add chopped nuts, oatmeal, dried berries. Mix the finished dough well and transfer to a bag.

This will make it most convenient for you to use it. Place the dough into molds with the expectation that it will rise by about one and a half times. Obviously, these are not real donuts (they are only deep-fried), so you can safely use any small-sized molds - make cupcakes, mini cupcakes and other options.

Bake at 180 degrees (top-bottom) until tender. Check with a skewer.

## Carrot cake
For cakes:
* 360 ml (1.5 cups) vegetable oil
* 200 g (4 pcs) eggs
* 300 g (2 cups) flour
* 460 g (2 cups) sugar
* 8 g (1 sachet) baking powder
* 15 g (2 tsp) baking soda
* 3 g (1/2 tsp) salt
* 12 grams (1.5 tsp) cinnamon
* 5 g (0.5 tsp) nutmeg
* 5 g (0.5 tsp) cloves
* 500 g of carrots, grated on a fine grater
* 200 g (1 cup) nuts
For the cream:
* 800 g of curd cheese
* 120 g icing sugar
* 150 ml cream 33%

First you need to combine vegetable oil with sugar. To do this, pour oil into the mixer bowl and add sugar. Beat at the maximum speed of the mixer for about 7 minutes, until the components are combined.

While the butter and sugar are beating, combine all dry ingredients in a separate bowl: sifted flour, salt, baking powder, soda, cinnamon, cloves, nutmeg. Stir well with a whisk until evenly spread.

When the butter and sugar have combined into a single emulsion, add the eggs one at a time, letting each egg dissolve completely (stir for 4-5 minutes). After all the eggs are added, you can add the dry mixture to the liquid one.

It is better to knead with a silicone spatula, since the mixture is not sticky and lumps are not formed during stirring. The result is a smooth, thick, but flowing dough.

It remains to add chopped nuts and grated carrots. It will be difficult to stir at first, but after a couple of minutes these ingredients will be evenly distributed throughout the mixture.

Fasten the bottom of the molds with baking paper and wrap in foil. Divide the mixture into three equal portions and place in separate baking tins. It is convenient to do this on a scale, for this you need to know the weight of the container in which all the ingredients were mixed. Spread the dough evenly with a spatula. Put in an oven preheated to 175 degrees, bake until tender for about 35 minutes.

Remove ready-made biscuits from the oven and let cool. Carefully cut out of the molds with a knife, remove the parchment from the bottom of the biscuits. We have got aromatic, juicy, porous biscuits. wrap in cling film, it is better to separate each cake, put in the refrigerator for several hours.

After the biscuits have cooled completely, you can start assembling the cake.

The recipe for the curd cream used for this cake can be found here.

Apply a small amount of cream to the cake base so that the cakes do not slip during assembly. Soak the cake with caramel (we took cherry), but you can not use the impregnation, since the biscuits are so juicy and bright.
Put some of the cream on the soaked biscuit, spread in an even layer, smooth the edges by going over the side of the cake with a spatula, trying to keep it perpendicular to the substrate.

Put the next cake and repeat the manipulation of the biscuit impregnation and cream application.

We complete the assembly of the cake with the last third biscuit, remembering to soak it. Apply the remaining cream to the top of the cake and the sides, closing all the small gaps.

We have got a delicious, tender, even cake in a "half-naked" coating. We leave it for an hour and a half in the refrigerator, so that the cream stiffens a little, and it is convenient to cut the cake. Decorate as desired (in our case, there were gingerbread cookies, some crushed nuts and fresh berries).

## Strawberry cake
For cake
* 225 g butter
* 225 g sugar
* 4 eggs
* 225 g self-rising flour (or 220 g plain flour + 1 tablespoon baking powder)
* 3 tbsp milk

For filling
* 300 ml heavy cream
* 300 g strawberries
* 100 ml strawberry jam

Beat the softened butter with sugar. Add the eggs one at a time, beating without stopping. The mass must be airy. Gently put in the flour, mix the dough with a spoon, drawing an eight: this way the mixture loses a minimum of air. Add milk. We bake for 1 hour in a greased form at a temperature of 160 degrees Celsius.

At this time, we rest. The cream is resting in the refrigerator. Cold cream is easier to whip.

We take the cake out of the oven, let it cool in the form for 15 minutes. We take it out of the mold and leave it to cool again. At this time, cut the strawberries into slices, whip the cream. Add strawberry jam to the whipped cream and mix slightly. Precisely slightly, so that the cream turns out beautiful streaks of jam, and not a solid pink mass.

Then everything is intuitively clear: cut the cake lengthwise into three parts, put half the cream and half the strawberries on the first layer. Put in the second layer, lay out the remaining cream and strawberries. Cover with a third layer and sprinkle with a spoonful of powdered sugar. We decorate (if we have time before it is eaten) with fresh strawberries.

## Cake with ricotta and pears

* 4-5 pears
* Dark sugar 2tsp
* 140 g butter
* 100 g sugar
* 1 egg
* 140 g ricota
* zest of 1 lemon
* 200 g flour (can be less)
* 10 g baking powder

Put paper in a split form, grease with oil and sprinkle with brown oil. Then lay out the chopped pear in slices.
Beat butter and sugar until white, add egg, ricotta and zest.
Sift flour (do not add all the flour at once! How much it will take), baking powder and vanilla sugar, mix everything until smooth.
Pour the dough over the pears and put them in the oven for 50-60 minutes at 180C.

## Cottage cheese cake with raspberries or apricots

* 2 eggs
* 75 g sugar
* Lemon zest
* 200 g cottage cheese
* 40 g starch
* 1 tablespoon ground almonds
* 200 g raspberries (can be frozen)

If the raspberries are frozen, remove them from the freezer at the beginning of the pie.
Beat eggs with sugar for several minutes until a fluffy light mass is obtained.
Add finely grated lemon zest.
Rub the cottage cheese through a sieve and hang with beaten eggs, add starch.
Place the dough in a greased dish and sprinkle with ground almonds or flour, spread the raspberries on top. Bake for 45-50 minutes at 180C.

## Rudolph's cookies for Christmas and New Year

* 280 g flour
* 100 g nut flour
* 130 g sugar
* A bit of salt
* 200 g cold butter
* 2 egg yolks
* Vanilla
* 1 tbsp of lemon juice
* Lemon zest

Mix all together into crumbles. Make a ball, split into several parts and put in fridge for 30 min.
Form biscits and bake on 175C, for 12-13 min. 

## Swedish chocolate cake

* 135 g butter
* 50 g cacao
* 180 g sugar
* 110 g flour
* 3 eggs

Melt butter, add everything step by step. 
Put in a baking form and bake on 180C until the first cracks. 

## Scones
for 20 scones
* 610 g flour T45
* 610 g flour T55
* 60 g baking powder
* 280 g powder sugar
* 4 g salt
* 60 g trimoline (inverted sugar)
* 280 g butter
* 400 g milk
* 240 g buttermilk
* 120 g white raisins

Mix all dry elements with butter in a standing mixer with a mixing tool. 
Change a mixing tool for a dough hook when butter disolves in dry ingredients. Add milk and buttermilk, mix for 3 min on Speed1, then 2 min on Speed2. 
Split the dough into two 

## Apple and cinnamon rolls

* 240+50 g flour
* 65 g warm milk
* 40 g butter
* 30 g sugar
* 1 egg yolk
* 1/2 sachet of yeast (or 10g of fresh yeast)
* 60 g water

For filling:
* 3 apples
* 60 g sugar
* 50 g butter
* 50 g blond raisins
* 1 tsp grounded cinnammon

For cream:
* 100 g sugar
* 100 g Philadelphia

In a mixing bowl (e.g., KitchenAid) mix yeast, water and warm milk, add 240 g of flour, sugar, salt and egg yolk, and mix it for 10 minutes. Add butter and mix another 5 minutes. Cover the dough with a film and put to rest for 2 hours. 

Peel apples, cut into slices and put in a saucepan with the butter, then add sugar, raisins and cinnammon. Cook for 15 minutes, often steering. Let it cool down.
Roll the dough into a rectangle shape on a dusted surface, spread the apple filling, roll it and cut into 9 buns. Cover a baking dish (25cm) with a baking paper and place all buns next to each other. Leave it rest for 1 hour. 
Heat the oven up to 180C. Place buns there for 25 minutes. 
Prepare the cream: whip cheese with sugar and leave it aside.
When buns are not hot, spread cream all over them. Enjoy!
