# Main dishes

## Broccoli baked in cream with cheese

* 1 head of broccoli
* 1 egg
* 100 ml cream 10%
* nutmeg (on the tip of a knife)
* a handful of cheese

Divide the broccoli into inflorescences and boil in boiling water for 3 minutes. Not more! This is enough for the initial heat treatment, while the broccoli remains crispy and tasty.Combine egg, cream and nutmeg.
Put broccoli in a mold, pour over the filling, sprinkle with grated cheese on top.
Bake in the oven for 15 minutes at 170C. 

## Adjarian Khachapuri (bread with cheese) - Acharuli

For 2-4 boats (depending on size)
Ingredients:

* 380-400 gr flour
* 200 ml warm water
* 100 ml milk
* 40 ml vegetable oil
* 1 tsp dry yeast
* 1 tsp salt
* 2 tsp sugar

For filling:
* 1 egg
* 200 gr suluguni (mozarella)
* 400 gr Imeretian cheese (feta + cheddar/parmezan)
* 50-70 ml milk or water
* 1.5 tbsp flour
* 2-4 yolks (depending on the number of boats)
* 50 gr butter (optional)

Preparation:
1. Dissolve the yeast with sugar in warm water, leave for 5 minutes. Add milk, mix and gradually add 200 g of flour, knead by hand or with a food processor until smooth, then gradually add the rest of the flour in the same way. (The dough should be collected in a ball, but with it is rather sticky). Add vegetable oil in parts and continue to knead. (The dough will become more obedient and smooth, slightly sticking to the fingers.) Then cover the dough with cling film or a towel, put in a warm place and let it increase at least twice. (You can also put it in the refrigerator for night if you are not going to bake everything at once)
2.Grate Imeretian cheese (you can replace it with Adyghe or vats, or at least feta). Add one egg, milk (water), flour, salt if necessary, if the cheese is not salted at all, mix everything into a homogeneous mass, it should be not dry, but like porridge.
3. Separately grate the suluguni on a coarse grater (can be replaced with mozzarella).
4. Divide the matched dough into 2-4 parts, depending on the size of the boat (khachapuri), form balls and leave for 10 minutes, covered with cling film or a towel. The dough will again become soft, pliable and more fluffy. Hands and work surface should be dusted with flour to work comfortably with the dough.
5.I recommend forming the boats directly on the parchment to make it easier to transfer to a baking sheet.

Forming No. 1:

With your fingers open the ball into a cake, while pressing only in the center of the cake, so that the edges remain thick and the center is thin ... Then take the cake in your hands and twist, stretching the dough (like on a pizza). Put again on the work surface, stretch the circle in a light oval, bring two edges of the dough to the middle, just pull the other two edges, lengthening the resulting shape of the dough, then connect. It turns out the shape of a "canoe" in which the edges are stuck together. Then open the center with your fingers, stretching the dough in width, forming the shape of a boat with sides .Put the cheese mass in the center of the boat, distribute and pour grated suluguni on top.

Forming No. 2

Open a uniform flat cake with your fingers, pick it up and stretch it slightly in all directions to make a thinner middle. Put the cheese mass on the cake, spread over the entire surface, leaving only the edges free. Wrap the sides of the cake, grabbing the cheese part. (As if you are wrapping a roll), while glue only the ends, creating the ends of the boat. Pour grated suluguni over the open cheese mass.

6. In a preheated oven (220 degrees) and a baking sheet, transfer the formed boats, bake for 15 minutes, until golden brown.
7. Remove the boats from the oven. Optionally, you can remove the excess dough from the khachapuri formed according to method No. 1. Separate the cheese part from the dough with a fork, pry it under the side and gently move the hand, remove the dough. Push cheese into the empty sides, put the yolk on top , then back into the oven for 1-2 minutes. And on the khachapuri formed according to the method No. 2, simply put the yolk on top and again in the oven for 1-2 minutes. If desired, after the oven, coat the edges of the dough with butter and serve hot with a piece oil next to szheltkom.


## Baked aubergines with mozzarella cheese
2 servings

* 1 medium aubergines
* 1 scoop of mozzarella
* 50 g parmesan
* 5-6 medium tomatoes (or a can of chopped tomatoes)
* 1 clove of garlic
* several sprigs of basil
* olive oil
* flour
* salt
* black pepper

Cut the aubergines into circles that are not too thick (about 0.5 cm), lightly add salt and place in a colander for about half an hour: during this time, as they say, excessively bitter juices will come out of them. Also slice the mozzarella thinly and grate the Parmesan cheese. Peel tomatoes (how to peel tomatoes) and cut into small pieces. Fry chopped garlic and basil stalk in a little olive oil, add chopped tomatoes and basil leaves, season with salt and pepper and simmer for 10-15 minutes over medium heat until the sauce thickens. Remove from heat and strain through a sieve or grind in a blender.

Rinse the aubergines, dry quickly, roll in flour and lightly fry in olive oil (aubergines tend to absorb oil like a sponge, so add some oil if necessary before loading the pan with the next portion). Transfer the fried aubergines to napkins to absorb the excess oil. Everything is ready to assemble our "tower": take a baking dish (best glass or ceramic), put a spoonful of tomato sauce on the bottom, place a slice of eggplant on top, put a slice of mozzarella on top and sprinkle with Parmesan. The next "floor" is tomato sauce, eggplant, cheese, and so on until you build as many towers as you plan to make eaters happy with this delicious dish. Bake the aubergines in an oven preheated to 220 degrees until the cheese melts on top into a golden crust (this will take 15-20 minutes), and serve immediately.

## Crispy Greek-style pie

* 200g bag spinach leaves
* 175g jar sundried tomato in oil
* 100g feta cheese, crumbled
* 2 eggs
* 0.5 250g pack filo pastry

Put the spinach into a large pan. Pour over a couple tbsp water, then cook until just wilted. Tip into a sieve, leave to cool a little, then squeeze out any excess water and roughly chop. Roughly chop the tomatoes and put into a bowl along with the spinach, feta and eggs. Mix well.

Carefully unroll the filo pastry. Cover with some damp sheets of kitchen paper to stop it drying out. Take a sheet of pastry and brush liberally with some of the sundried tomato oil. Drape oil-side down in a 22cm loosebottomed cake tin so that some of the pastry hangs over the side. Brush oil on another piece of pastry and place in the tin, just a little further round. Keep placing the pastry pieces in the tin until you have roughly three layers, then spoon over the filling. Pull the sides into the middle, scrunch up and make sure the filling is covered. Brush with a little more oil.

Heat oven to 180C/fan 160C/gas 4. Cook the pie for 30 mins until the pastry is crisp and golden brown. Remove from the cake tin, slice into wedges and serve with salad.

## Lamb-stuffed aubergines with Moorish spices and Manchego cheese

* 4 aubergines
* 6 tbsp olive oil
* 1 onion, chopped
* 4 garlic cloves, finely chopped
* 1 large red pepper, seeds removed, chopped
* 1½ tsp freshly ground cumin seeds
* 1 tsp ground cinnamon
* ½ tsp freshly grated nutmeg
* 1 tsp pimentón dulce (smoked sweet Spanish paprika)
* large pinch of crushed dried chillies
* 500g/1lb 2oz lamb mince
* 6 tbsp tomato sauce (see Top recipe tip below)
* 100g/3½oz Manchego cheese, coarsely grated
* salt and freshly ground black pepper

Preheat the oven to 200C/400F/Gas 6.
Cut each aubergine lengthways through the stalk, then score the flesh in a tight criss-cross pattern, taking the knife through the flesh down to the skin, but taking care not to cut through the skin. Place them side by side on a baking tray and drizzle each half with half a tablespoon of the oil, season with salt and bake for 30-40 minutes or until the flesh is soft and tender but not browned.
Meanwhile, heat the remaining two tablespoons of oil in a large non-stick frying pan. Add the onion, garlic, red pepper and spices and fry gently for 10 minutes. Add the lamb mince and fry for 3–4 minutes or until all the meat is lightly browned. Stir in the tomato sauce and simmer for five minutes.
Remove the aubergines from the oven and increase the temperature to 220C/425F/Gas 7. Carefully scoop most of the flesh out of the baked aubergine halves, leaving the skins with a layer of flesh about 1cm/½in thick. Stir the scooped-out flesh into the lamb mixture with half a teaspoon of salt and some pepper to taste. Spoon the mixture into each aubergine shell and sprinkle with the grated cheese. Bake in the oven for 8–10 minutes, or until the cheese is bubbling and golden-brown.
## Simple baked lasagne

* 2 carrots , peeled
* 2 onions , peeled
* 2 cloves of garlic , peeled
* 2 sticks of celery , trimmed
* olive oil
* 2 rashers of higher-welfare smoked streaky bacon
* ½ a bunch of fresh thyme
* 500 g quality beef mince
* a good splash of red wine
* 1 gluten-free beef stock cube , preferably organic
* 2 x 400 g tins of plum tomatoes
* sea salt
* freshly ground black pepper
* 1 x gluten-free pasta dough

* 3 anchovy fillets , from sustainable sources
* 500 ml crème fraîche
* 2 handfuls of freshly grated Parmesan cheese
* milk , optional

To make the Bolognese sauce, finely chop the carrots, onions, garlic and celery and add to a large, wide pan over a medium heat with a drizzle of olive oil. Roughly chop and add the bacon, then pick in the thyme leaves and cook for 5 to 10 minutes, or until softened and lightly golden.
Turn the heat up slightly, then stir in the beef mince, breaking it up with a wooden spoon. Cook for around 5 minutes, or until browned all over. Add the wine and crumble in the stock cube, stirring continuously until the liquid has completely reduced. Stir in the tomatoes and 1 tin’s worth of water and bring to the boil. Reduce to a simmer, cover and cook for around 1 hour, then remove the lid and continue cooking for 30 minutes, or until thickened and reduced.
Meanwhile, preheat the oven to 180ºC/350ºF/gas 4. 
For the white sauce, finely chop the anchovies, then mix with the crème fraîche and a handful of Parmesan, then season with salt and pepper – you may need to loosen the mixture with a little milk.
Cut the sheets of pasta into rectangles (roughly 10cm x 15cm).
Spoon one-third of the Bolognese sauce into an ovenproof dish (roughly 25cm x 30cm). Layer over one-third of the lasagne sheets and top with one-third of the béchamel sauce. Repeat with the remaining ingredients until you have three layers in total, finishing with a final layer of béchamel. Grate over the remaining Parmesan and drizzle with olive oil, then cover with tin foil. Place in the hot oven for around 20 minutes, remove the foil and continue cooking for around 30 minutes, or until golden and bubbling. Serve with a nice, crisp salad.
## Kung Pao chicken

* 1 tablespoon Szechuan peppercorns
* 2½ tablespoons cornflour
* 4 skinless higher-welfare chicken thighs , (350g)
* groundnut oil , or vegetable oil
* 4 cloves of garlic
* 5 cm piece of ginger
* 2 spring onions
* 6 dried red chillies
* 2 tablespoons low-salt soy sauce
* ½ tablespoon rice wine vinegar
* 1 heaped tablespoon runny honey
* 50 g unsalted peanuts
* 1 punnet of salad cress

Toast the Szechuan peppercorns in a dry frying pan until lightly golden. Transfer to a pestle and mortar, grind to a fine powder, then sieve into a large bowl, discarding any large, tough bits.
Add 2 tablespoons of cornflour and stir to combine. Chop the chicken into bite-sized chunks, then toss in the cornflour mixture to coat.
Pour 2cm of oil into a large non-stick frying pan over a medium heat, add the chicken and fry for 7 to 8 minutes, or until golden and cooked through.
Meanwhile, peel and finely slice the garlic and ginger, then trim and finely slice the spring onions.
Using a slotted spoon, remove the chicken to a double layer of kitchen paper to drain. Carefully remove and discard most of the oil, leaving about 2 tablespoons in the pan, then return to a medium heat.
Add the garlic and ginger and fry for 2 minutes, or until lightly golden, then stir in the spring onions and whole chillies and fry for 1 further minute.
Meanwhile, combine ½ tablespoon of cornflour and 2 tablespoons of water. Mix in the soy, vinegar and honey, then pour the mixture into the pan. Bring to the boil and simmer for a few minutes, or until slightly thickened.
Lightly bash and add the peanuts, stir in the chicken, then toss well until warmed through. Snip the cress over the ribbon salad, scatter the reserved coriander leaves over the chicken, then serve.
## Turkey con chilli

* olive oil
* 2 red onions , peeled and roughly chopped
* 1 carrot , peeled and roughly chopped
* 1 leek , trimmed and roughly chopped
* 1 red pepper , deseeded and roughly chopped
* 1 yellow pepper , deseeded and roughly chopped
* 1 fresh red chilli , deseeded and finely chopped
* 1 fresh green chilli , deseeded and finely chopped
* 1 bunch fresh coriander , stalks finely chopped, leaves picked
* 1 teaspoon ground cumin
* 1 heaped teaspoon smoked paprika
* 1 heaped teaspoon runny honey , optional
* 3 tablespoons white wine vinegar , optional
* 600 g turkey , leftover, shredded
* sea salt
* freshly ground black pepper
* 3 x 400 g tinned chopped tomatoes
* 400 g tinned butter beans or chickpeas , drained
* 2 limes , juice of
* soured cream , to serve
FOR THE GUACAMOLE
* 2 ripe avocados , peeled and destoned
* 2 tomatoes , halved
* ¼ red onion , peeled
* ½ clove garlic , peeled
* 1 fresh green chilli , deseeded
* 1 bunch fresh coriander
* 1 lime

Preheat the oven to 180ºC/350ºF/gas 4. Heat a few lugs of olive oil in a large casserole-type pan on a medium heat. Add the onions, carrot, leek, peppers and chillies, and cook, stirring occasionally, for about 5 minutes. Add the coriander stalks, cumin and paprika, and cook for another 10 minutes or so, stirring frequently until soft and delicious. Sometimes I like to add some honey and white wine vinegar at this point and let it cook for a couple of minutes. I find this adds a wonderful sheen and enhances the natural sweetness of the vegetables. 
While that’s happening, shred the turkey meat off your carcass and roughly chop it. Add a good pinch of salt and pepper to the pan of vegetables, then add the turkey and take the pan off the heat. Add the tomatoes and chickpeas or butter beans and stir everything together. Pop it in the hot oven to blip away for 2 hours. Check on it after an hour, and add a splash of water if it looks a bit dry.
While that’s cooking, make your guacamole by blitzing one of your avocados in a food processor with the tomatoes, onion, garlic, chilli and coriander. Use a fork to mash the other avocado in a bowl so it’s nice and chunky. Taste the mixture in the food processor and add salt and squeezes of lime juice until the taste is just right for you. Whiz up one more time then tip into the bowl with your chunky avocado and mix together.
Take the chilli out of the oven and scrape all the gnarly bits from the edge of the pan back into the chilli for added flavour. Squeeze in some lime juice, and stir through most of the coriander leaves. Have a taste to check the seasoning then serve with steamed basmati rice or tortillas, and a good dollop of soured cream and guacamole on top. Scatter over your remaining coriander leaves and some finely sliced fresh chilli if you fancy then get everyone to tuck in.

## Prawn & chorizo orzo

* 2 cloves of garlic
* 200 g quality chorizo
* 0.5 a bunch of fresh basil (15g)
* 4 tablespoons olive oil
* 2 tablespoons sherry vinegar
* 400 ml passata
* 300 g orzo
* 200 g cherry tomatoes, on the vine
* 400 g large cooked peeled king prawns ,from sustainable sources

Preheat the oven to 180ºC/350ºF/gas 4.

Peel and finely chop the garlic, and slice the chorizo. Pick and finely chop the basil.

Heat half the oil in a heavy-based pan. Fry the garlic and chorizo for 3 minutes, then deglaze the pan with the vinegar.

Add the passata and 300ml of water, then the orzo. Bring to the boil, reduce the heat and simmer for 10 to 15 minutes, or until the orzo is al dente, stirring occasionally to prevent it sticking.

Spread the cherry tomatoes over a baking tray, drizzle with the rest of the oil and season. Roast for 10 minutes, or until soft.

Stir half the basil into the pasta, along with the prawns. Divide between bowls, top with the remaining basil and serve the roasted tomatoes alongside.

## Chicken kiev

* 4 rashers of smoked streaky bacon
* olive oil
* 4 x 150 g skinless chicken breasts , (I got mine from the butcher with the bone in, but either way is fine)
* 3 tablespoons plain flour
* 2 large free-range eggs
* 150 g fresh breadcrumbs
* sunflower oil
* 2 large handfuls of baby spinach , or rocket
* 2 lemons
* BUTTER
* 4 cloves of garlic
* ½ a bunch of fresh flat-leaf parsley (15g)
* 4 knobs of unsalted butter , (at room temperature)
* 1 pinch of cayenne pepper

Fry the bacon in a pan on a medium heat with a tiny drizzle of olive oil, until golden and crisp, then remove.
For the butter, peel the garlic, then finely chop with the parsley leaves and mix into the softened butter with the cayenne. Firm up in the fridge.
Working one-by-one on a board, stuff the chicken breasts. To do this, start by pulling back the loose fillet on the back of the breast – put your knife in the opposite direction and slice to create a long pocket (for extra guidance, watch the how-to video below).
Open the pocket up with your fingers, cut the chilled butter into four and push one piece into the pocket, then crumble in a rasher of crispy bacon. Fold and seal back the chicken, completely covering the butter and giving you a nice neat parcel. Repeat with the 3 remaining breasts.
Preheat the oven to 180°C/350°F/gas 4.
Place the flour in one shallow bowl, whisk the eggs in another, and put the breadcrumbs and a pinch of seasoning into a third. Evenly coat each chicken breast in flour, then beaten egg, letting any excess drip off, and finally, turn them in the breadcrumbs, patting them on until evenly coated.
Shallow-fry in 2cm of sunflower oil on a medium to high heat for a couple of minutes on each side, or until lightly golden, then transfer to a tray and bake in the oven for 10 minutes, or until cooked through. You can bake them completely in the oven and skip the frying altogether, you just need to drizzle them with olive oil and bake for about 20 minutes – they won’t be as golden, but they’ll be just as delicious.
Meanwhile, peel and roughly chop the potatoes and cook in a large pan of boiling salted water for 12 to 15 minutes, or until tender.
Chop up the broccoli and add it to the potatoes for the last 8 minutes. Drain and leave to steam dry, then return to the pan and mash with a knob of butter and a pinch of salt and pepper.
Divide the mash between your plates and place a Kiev on top of each portion. Lightly dress the spinach leaves or rocket in a little oil and lemon juice, then sprinkle over the top as a salady garnish. Serve with a wedge of lemon on the side.

## Farfalle with carbonara and spring peas

* 455 g farfalle
* 1 free-range egg
* 100 ml double cream
* 12 rashers of higher-welfare pancetta or smoked streaky bacon
* 3 handfuls of fresh podded or frozen peas
* 2 sprigs of fresh mint
* 2 handfuls of Parmesan cheese

First of all, bring a large pan of salted water to the boil, add the farfalle, and cook according to the packet instructions.
Whisk the egg in a bowl with the cream and season with sea salt and black pepper.
Roughly slice your pancetta or bacon and put it into a second pan over a medium heat and cook until crispy and golden.
When the farfalle is nearly cooked, add the peas for the last minute and a half. This way they will burst in your mouth and be lovely and sweet. When cooked, drain in a colander, saving a little of the cooking water.
Add the pasta to the pancetta. Pick and finely slice the mint leaves and stir in most of them. If the pan isn't big enough, mix it all together in a large warmed bowl.
Now you need to add the egg and cream mix to the pasta. What's important here is that you add it while the pasta is still hot. This way, the residual heat of the pasta will cook the eggs, but not so that they resemble scrambled eggs, as I've seen in some dodgy old restaurants on the motorway! The pasta will actually cook the egg enough to give you a silky smooth sauce. Toss together and loosen with a little of the reserved cooking water if necessary.
Season with salt and pepper, grate over the Parmesan and sprinkle over the rest of the mint leaves, and serve as soon as possible.

## Taiwanese 3 Cup Chicken

* 1 - 1 1/2 lb. chicken drumettes 
* 15 - 20 cloves of garlic, peeled
* 1 small piece of ginger, sliced
* fresh Thai basil leaves (red basil)

For the Sauce:
* 1/3 cup of soy sauce (low sodium)
* 1/3 cup rice wine
* 1/3 cup of Asian sesame oil
* 3 Tbsp. cane sugar
* 1 tsp. dried chili flakes (or fresh red chilis)
* 1/2 tsp. salt

Brown the chicken for a few minutes first before adding the sauce mixture.
Cook the sauce mixture and chicken for 15 - 20 min. or until almost done.
When almost done, add the fresh basil leaves and stir fry, then cover with a lid for 1 min.
Transfer to a serving bowl and serve hot.

## Quiche with salmon, brocolli and blue cheese

* 175 g flour
* 100g butter
* 2 tbsp cold water
* 1 egg yolk
* Salt

* 300 g salmon
* 200 g brocolli
* 70 g blue cheese/ gorgonzola
* 3 eggs
* 250 g sour cream / fraiche cream or double cream
* Salt, pepper, herbs, thyme

10-15 minutes before preparing the dough, put water and butter in the freezer. 
Grate the butter on a coarse grater, stir with flour and add salt, water and yolk, quickly knead the dough for a short time until it can be collected into a ball. Wrap it in a cling film and cooled in a fridge for 30-40 minutes.
Cover the bottom of the mold with baking paper, roll out the dough between two sheets of parchment to a thickness of 3 mm, put in a mold with a diameter of 18-20 cm, make sides 4-5 cm high, prick with a fork, put in the freezer for 10 minutes.
Put a sheet of baking paper on the dough and load it with either dry rice or peas (to create a heavy weight to keep dough in place). Bake at 200C for 15 minutes with weight and 10 minutes without, until the base is lightly browned.
For pouring: mix eggs, sour cream, salt and pepper, herbs and crumble the cheese. Divide the broccoli into inflorescences and cut the fish into pieces.
When the base is ready, lay out the filling, pour the filling on top and sprinkle with some cheese (additional). Bake at 200 C for 40-50 minutes. Let cool for 15-20 minutes, you can cut it.

