# Breakfast recipes

## Crepes
for two

* 2 eggs
* 1 glass of water
* 1 glass of milk
* 1 cup self-rising flour
* 2 tbsp sugar (optional)
* 2 tbsp vegetable oil

Beat eggs with sugar (if using). Add a glass of hot water, whisking with a mixer, then a glass of flour and a glass of warm milk.
Add butter to the dough. Fry in a hot skillet without adding oil.

## True Belgian Waffles

* 2 cups all-purpose flour
* 0.75 cup sugar
* 3.5 teaspoons baking powder
* 2 large eggs, separated
* 1.5 cups whole milk
* 1 cup butter, melted
* 1 teaspoon vanilla extract
* Sliced fresh strawberries or syrup

In a bowl, combine flour, sugar and baking powder. In another bowl, lightly beat egg yolks. Add milk, butter and vanilla; mix well. Stir into dry ingredients just until combined. Beat egg whites until stiff peaks form; fold into batter.

Bake in a preheated waffle iron according to manufacturer's directions until golden brown. Serve with strawberries or syrup.

## Gluten-free pancakes/waffles

* 130 g Yougurt
* 2 eggs
* 4 tbsp flour
* 0.5 tsp
* Salt

Mix together and cook either on a pan or in a waffle maker without oil.

## Cottage cheese pancakes

* 200-250 g cottage cheese
* 1 egg
* 4-5 tbsp semolina/flour
* vanilla

Mix all together and form small balls (around 6-8 items) and bake it until golden. Or cook it on a pan from both sides until golden on medium heat.
